### ISSUE TITLE
Failed to be enabled for Godot 4.1.2

### ISSUE THREAD

**Issue by powof2** [Delsin-Yu/GD-AtlasTexture-Creator#1]
Hi, 
Thanks for the great tool. but it won't be enabled for Godot 4.1.2, Godot will report:
```
Unable to load addon script from path: 'res://addons/deyu_atlas_texture_creator_window/UnityAtlasTextureCreatorBoot.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/deyu_atlas_texture_creator_window/plugin.cfg' to prevent further errors.
``` 
Godot Version: 4.1.2 stable, with c# support.

Thank you.

**Comment by powof2** [comment]
And the debugger says:
```
E 0:00:02:0316   can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://addons/deyu_atlas_texture_creator_window/UnityAtlasTextureCreator.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/mono/csharp_script.cpp:2388 @ can_instantiate()
```

**Comment by Delsin-Yu** [comment]
Let me see

**Comment by Delsin-Yu** [comment]
It looks like in order for any .Net-based plugins to work you need to first build the .Net project once, I have added additional instructions to the readme documentation.

> Configure the .Net runtime according to the Prerequisites section of the [Godot Engine Docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html).
> ...
> If you have not yet create a C# solution, select Project/Tools/C#/Create C# solution, then click the Build button at top right corner.
